apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pcb-netlist-visualizer-api.fullname" . }}
spec:
  ingressClassName: nginx
  tls:
      {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: pcb-netlist-visualizer-api
                port:
                  number: {{ $.Values.service.port }}
      {{- end }}
  {{- end }}