apiVersion: v1
kind: Service
metadata:
  name: pcb-netlist-visualizer-client
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "pcb-netlist-visualizer-client.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000